// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Loads .env.local (this project's convention for local secrets, matching
// Next.js's own env loading and the existing Clerk variables) instead of a
// bare .env, so `DATABASE_URL` lives in the same file as everything else.
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
